# SYNTAX 2K26 — One-Click cPanel Deploy Script
# Run this from the cseworkshop/ root folder:
#   PowerShell: .\deploy.ps1

Write-Host ""
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host "  SYNTAX 2K26 — cPanel Deploy Builder" -ForegroundColor Cyan
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host ""

# ── Step 1: Build React app ────────────────────────────────────────────
Write-Host "[1/3] Building React app..." -ForegroundColor Yellow
Set-Location frontend
npm install --silent
npm run build
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Build failed. Fix errors above and retry." -ForegroundColor Red
    exit 1
}
Set-Location ..
Write-Host "      Build complete." -ForegroundColor Green

# ── Step 2: Create deploy package ─────────────────────────────────────
Write-Host "[2/3] Creating deploy package..." -ForegroundColor Yellow

$deployDir = "deploy_package"
$zipName   = "syntax2k26_cpanel.zip"

# Remove old package if exists
if (Test-Path $deployDir)  { Remove-Item -Recurse -Force $deployDir }
if (Test-Path $zipName)    { Remove-Item -Force $zipName }

New-Item -ItemType Directory -Path $deployDir | Out-Null

# Files to include (from project root — these go directly into public_html)
$include = @(
    ".htaccess",
    "index.html",       # generated by Vite build
    "reactapp"          # generated by Vite build
)

foreach ($item in $include) {
    if (Test-Path $item) {
        Copy-Item -Recurse -Force $item "$deployDir\"
    }
}

# Backend folders (always needed)
$backendFolders = @("api", "includes", "database", "assets")
foreach ($folder in $backendFolders) {
    if (Test-Path $folder) {
        Copy-Item -Recurse -Force $folder "$deployDir\"
    }
}

# Create empty uploads folder (needed by PHP)
New-Item -ItemType Directory -Force "$deployDir\uploads" | Out-Null
New-Item -ItemType File -Force "$deployDir\uploads\.gitkeep" | Out-Null

# ── Step 3: Zip it ────────────────────────────────────────────────────
Write-Host "[3/3] Zipping to $zipName ..." -ForegroundColor Yellow
Compress-Archive -Path "$deployDir\*" -DestinationPath $zipName -Force

# Cleanup temp dir
Remove-Item -Recurse -Force $deployDir

Write-Host ""
Write-Host "==========================================" -ForegroundColor Green
Write-Host "  DONE! File ready: $zipName" -ForegroundColor Green
Write-Host "==========================================" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Upload $zipName to cPanel File Manager > public_html" -ForegroundColor White
Write-Host "  2. Extract it there (right-click > Extract)" -ForegroundColor White
Write-Host "  3. Edit includes/config.php with your DB credentials" -ForegroundColor White
Write-Host "  4. Import database/nscet_symposium.sql via phpMyAdmin" -ForegroundColor White
Write-Host "  5. Visit your domain — done!" -ForegroundColor White
Write-Host ""
