# SYNTAX 2K26 — One-Click cPanel Deploy Script
# Run this from the cseworkshop/ root folder:
#   PowerShell: .\deploy.ps1
#
# Output: syntax2k26_cpanel.zip
# Upload to cPanel > public_html > Extract
# Site will be live at: https://yourdomain.com/syntax2k26

Write-Host ""
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host "  SYNTAX 2K26 — cPanel Deploy Builder" -ForegroundColor Cyan
Write-Host "  Output folder: /syntax2k26/" -ForegroundColor Cyan
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host ""

# ── Step 1: Build React app ────────────────────────────────────────────
Write-Host "[1/3] Building React app..." -ForegroundColor Yellow
Set-Location frontend
npm install --silent
npm run build
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Build failed. Fix errors above and retry." -ForegroundColor Red
    Set-Location ..
    exit 1
}
Set-Location ..
Write-Host "      Build complete." -ForegroundColor Green

# ── Step 2: Package into syntax2k26/ subfolder ────────────────────────
Write-Host "[2/3] Packaging files into syntax2k26/ folder..." -ForegroundColor Yellow

$subFolder  = "syntax2k26"       # ← folder name on cPanel (yourdomain.com/syntax2k26)
$deployDir  = "deploy_package"
$zipName    = "syntax2k26_cpanel.zip"
$destFolder = "$deployDir\$subFolder"

# Clean old package
if (Test-Path $deployDir) { Remove-Item -Recurse -Force $deployDir }
if (Test-Path $zipName)   { Remove-Item -Force $zipName }

New-Item -ItemType Directory -Path $destFolder | Out-Null

# React build output (generated by Vite into project root)
$reactFiles = @("index.html", "reactapp")
foreach ($item in $reactFiles) {
    if (Test-Path $item) {
        Copy-Item -Recurse -Force $item "$destFolder\"
    }
}

# PHP backend folders
$backendFolders = @("api", "includes", "database", "assets")
foreach ($folder in $backendFolders) {
    if (Test-Path $folder) {
        Copy-Item -Recurse -Force $folder "$destFolder\"
    }
}

# .htaccess (SPA routing)
Copy-Item -Force ".htaccess" "$destFolder\"

# Empty uploads folder
New-Item -ItemType Directory -Force "$destFolder\uploads" | Out-Null
New-Item -ItemType File -Force "$destFolder\uploads\.gitkeep" | Out-Null

# ── Step 3: Zip ───────────────────────────────────────────────────────
Write-Host "[3/3] Creating $zipName ..." -ForegroundColor Yellow
Compress-Archive -Path "$deployDir\*" -DestinationPath $zipName -Force
Remove-Item -Recurse -Force $deployDir

Write-Host ""
Write-Host "==========================================" -ForegroundColor Green
Write-Host "  SUCCESS! File ready: $zipName" -ForegroundColor Green
Write-Host "==========================================" -ForegroundColor Green
Write-Host ""
Write-Host "HOW TO DEPLOY:" -ForegroundColor Cyan
Write-Host "  1. Login to cPanel -> File Manager -> public_html" -ForegroundColor White
Write-Host "  2. Upload $zipName" -ForegroundColor White
Write-Host "  3. Right-click the ZIP -> Extract" -ForegroundColor White
Write-Host "     (This creates public_html/syntax2k26/ automatically)" -ForegroundColor Gray
Write-Host "  4. Edit public_html/syntax2k26/includes/config.php" -ForegroundColor White
Write-Host "     with your database name, username and password" -ForegroundColor Gray
Write-Host "  5. Open phpMyAdmin -> select your DB -> Import" -ForegroundColor White
Write-Host "     -> choose syntax2k26/database/nscet_symposium.sql" -ForegroundColor Gray
Write-Host "  6. Visit: https://yourdomain.com/syntax2k26" -ForegroundColor Green
Write-Host ""
